export type Language = 'en' | 'es';

export const translations = {
  en: {
    // Navigation
    nav: {
      home: 'Home',
      about: 'What´s this think?',
      portfolio: 'Interpretations',
      services: 'Process',
      fantasma: 'FNTSM',
      experience: 'Experience',
      contact: 'Contact',
    },
    // Hero Section
    hero: {
      title: 'RANDOM',
      subtitle: 'A crossover between creativity and technology through the techniques of Machinima and Experimental 3D Cinema.',
      description: '',
      viewPortfolio: 'Dreams',
      getInTouch: 'Nightmares',
    },
    // About Section
    about: {
      title: 'What´s this think?',
      description1: "In the world of the unexpected, the interplay between control and chaos is explored, reflecting how randomness can give rise to creativity beyond expectations. Here, machinima becomes a tool to capture the very essence of unpredictability.",
      description2: "Dreams generated through the technique of machinima are presented. The narrative unfolds unpredictably, challenging the notions of control and authorship in artistic creation.",
      description3: "Dreams and technology converge. Images generated by machinima and video games merge with dreamlike narratives, creating alternative and apocalyptic realities. The works presented here challenge conventions and linear storytelling.",
      coreStrengths: 'Core Strengths',
      skills: {
        creativeThinking: 'Creative Thinking',
        problemSolving: 'Problem Solving',
        userExperience: 'User Experience',
        innovation: 'Innovation',
      },
    },
    // Portfolio Section
    portfolio: {
      title: 'Interpretations',
      description: 'A collection of organic digital experiences that blend creativity with functionality',
      projects: {
        organicEcommerce: {
          title: 'Organic E-commerce',
          description: 'A sustainable shopping platform with fluid animations and natural design patterns.',
        },
        motionStudio: {
          title: 'Motion Studio',
          description: 'Creative agency website featuring advanced parallax effects and smooth transitions.',
        },
        forestDashboard: {
          title: 'Forest Dashboard',
          description: 'Environmental monitoring dashboard with organic data visualizations.',
        },
        naturePortfolio: {
          title: 'Nature Portfolio',
          description: 'Photography portfolio with immersive scroll experiences and fluid layouts.',
        },
      },
    },
    // Services Section
    services: {
      title: 'Process',
      description: 'Comprehensive digital solutions that combine technical expertise with creative vision',
      webDevelopment: {
        title: 'Web Development',
        description: 'Custom websites and applications built with modern technologies and organic design principles.',
        features: ['React & Next.js', 'Node.js Backend', 'Database Integration', 'API Development'],
      },
      uiuxDesign: {
        title: 'UI/UX Design',
        description: 'Beautiful, intuitive interfaces that follow natural design patterns and enhance user experience.',
        features: ['User Research', 'Wireframing', 'Prototyping', 'Design Systems'],
      },
      mobileDevelopment: {
        title: 'Mobile Development',
        description: 'Responsive web applications and native mobile apps optimized for all devices.',
        features: ['Progressive Web Apps', 'React Native', 'Cross-platform', 'App Store Deployment'],
      },
      performanceOptimization: {
        title: 'Performance Optimization',
        description: 'Speed up your website and improve user experience with advanced optimization techniques.',
        features: ['Core Web Vitals', 'Code Splitting', 'Image Optimization', 'Caching Strategies'],
      },
      seoAnalytics: {
        title: 'SEO & Analytics',
        description: 'Improve your online visibility and track performance with comprehensive SEO and analytics.',
        features: ['Technical SEO', 'Google Analytics', 'Search Console', 'Performance Monitoring'],
      },
      consultation: {
        title: 'Consultation',
        description: 'Strategic guidance for your digital projects, from concept to successful implementation.',
        features: ['Project Planning', 'Tech Stack Selection', 'Architecture Design', 'Team Training'],
      },
    },
    // FANTASMA Section
    fantasma: {
      title: 'FANTASMA',
      description: 'Exploring the intersection of dreams and digital reality through machinima',
      projects: {
        dreamscape: {
          title: 'Digital Dreamscape',
          description: 'An exploration of subconscious narratives through interactive media.',
        },
        chaos: {
          title: 'Controlled Chaos',
          description: 'Where randomness meets intention in digital storytelling.',
        },
        convergence: {
          title: 'Reality Convergence',
          description: 'The merging of virtual and dream worlds in machinima form.',
        },
      },
    },
    // Experience Section
    experience: {
      title: 'Experience',
      description: 'A journey through creative development and digital innovation',
      stats: {
        projectsCompleted: 'Projects Completed',
        yearsExperience: 'Years Experience',
        happyClients: 'Happy Clients',
        clientSatisfaction: 'Client Satisfaction',
      },
      jobs: {
        seniorCreativeDeveloper: {
          title: 'Senior Creative Developer',
          company: 'Digital Organic Studio',
          location: 'Remote',
          period: '2022 - Present',
          description: 'Leading the development of innovative web experiences with focus on organic design and smooth animations.',
          achievements: [
            'Increased client satisfaction by 40% through improved UX',
            'Reduced page load times by 60% across all projects',
            'Mentored 5 junior developers',
          ],
        },
        fullStackDeveloper: {
          title: 'Full-Stack Developer',
          company: 'Nature Tech Solutions',
          location: 'San Francisco, CA',
          period: '2020 - 2022',
          description: 'Developed scalable web applications with emphasis on environmental monitoring and data visualization.',
          achievements: [
            'Built real-time dashboard serving 10k+ users',
            'Implemented ML algorithms for predictive analytics',
            'Led migration to microservices architecture',
          ],
        },
        frontendDeveloper: {
          title: 'Frontend Developer',
          company: 'Creative Labs',
          location: 'New York, NY',
          period: '2018 - 2020',
          description: 'Specialized in creating responsive, accessible websites with modern JavaScript frameworks.',
          achievements: [
            'Improved accessibility scores by 85%',
            'Reduced development time by 30% with reusable components',
            'Collaborated with design team on 50+ projects',
          ],
        },
      },
      keyAchievements: 'Key Achievements:',
    },
    // Contact Section
    contact: {
      title: "Let's Connect",
      description: "Ready to bring your ideas to life? Let's create something amazing together.",
      getInTouch: 'Get in Touch',
      intro: "I'm always excited to discuss new projects and opportunities. Whether you have a specific idea in mind or need guidance on your digital journey, I'm here to help.",
      contactInfo: {
        email: 'Email',
        phone: 'Phone',
        location: 'Location',
      },
      followMe: 'Follow Me',
      form: {
        name: 'Name',
        namePlaceholder: 'Your name',
        email: 'Email',
        emailPlaceholder: 'your.email@example.com',
        subject: 'Subject',
        subjectPlaceholder: "What's this about?",
        message: 'Message',
        messagePlaceholder: 'Tell me about your project...',
        sendMessage: 'Send Message',
      },
    },
    // Footer
    footer: {
      copyright: '© 2025 RANDOM. Crafted with organic design principles.',
    },
  },
  es: {
    // Navigation
    nav: {
      home: 'Inicio',
      about: 'Qué es esta cosa?',
      portfolio: 'Interpretaciones',
      services: 'Proceso',
      fantasma: 'FNTSM',
      experience: 'Experiencia',
      contact: 'Contacto',
    },
    // Hero Section
    hero: {
      title: 'RANDOM',
      subtitle: 'Cruce entre la creatividad y la tecnología a través de la técnica del Machinima y el Cine 3D Experimental.',
      description: '',
      viewPortfolio: 'Sueños',
      getInTouch: 'Pesadillas',
    },
    // About Section
    about: {
      title: 'Qué es esta cosa?',
      description1: 'En el mundo de lo inesperado exploramos la interacción entre el control y el caos, reflejando cómo la aleatoriedad puede dar lugar a la creatividad más allá de nuestras expectativas. Aquí, veremos cómo el machinima se convierte en una herramienta para capturar la esencia misma de lo impredecible.',
      description2: 'Sueños generados por la técnica del machinima se presentan. La narrativa se desarrolla de manera impredecible, desafiando la noción de control y autoría en la creación artística.',
      description3: 'Los sueños y la tecnología convergen. Las imágenes generadas por la técnica del machinima y el videojuego se combinan con la narrativa onírica, creando realidades alternativas y apocalípticas. Las obras aquí presentes desafían las convenciones y narrativas lineales.',
      coreStrengths: 'Fortalezas Principales',
      skills: {
        creativeThinking: 'Pensamiento Creativo',
        problemSolving: 'Resolución de Problemas',
        userExperience: 'Experiencia de Usuario',
        innovation: 'Innovación',
      },
    },
    // Portfolio Section
    portfolio: {
      title: 'Interpretaciones',
      description: 'Una colección de experiencias digitales orgánicas que combinan creatividad con funcionalidad',
      projects: {
        organicEcommerce: {
          title: 'E-commerce Orgánico',
          description: 'Una plataforma de compras sostenible con animaciones fluidas y patrones de diseño natural.',
        },
        motionStudio: {
          title: 'Motion Studio',
          description: 'Sitio web de agencia creativa con efectos parallax avanzados y transiciones suaves.',
        },
        forestDashboard: {
          title: 'Dashboard Forestal',
          description: 'Panel de monitoreo ambiental con visualizaciones de datos orgánicas.',
        },
        naturePortfolio: {
          title: 'Portafolio Natural',
          description: 'Portafolio de fotografía con experiencias de scroll inmersivas y diseños fluidos.',
        },
      },
    },
    // Services Section
    services: {
      title: 'Proceso',
      description: 'Soluciones digitales integrales que combinan experiencia técnica con visión creativa',
      webDevelopment: {
        title: 'Desarrollo Web',
        description: 'Sitios web y aplicaciones personalizadas construidas con tecnologías modernas y principios de diseño orgánico.',
        features: ['React & Next.js', 'Backend Node.js', 'Integración de Base de Datos', 'Desarrollo de API'],
      },
      uiuxDesign: {
        title: 'Diseño UI/UX',
        description: 'Interfaces hermosas e intuitivas que siguen patrones de diseño natural y mejoran la experiencia del usuario.',
        features: ['Investigación de Usuario', 'Wireframing', 'Prototipado', 'Sistemas de Diseño'],
      },
      mobileDevelopment: {
        title: 'Desarrollo Móvil',
        description: 'Aplicaciones web responsivas y aplicaciones móviles nativas optimizadas para todos los dispositivos.',
        features: ['Progressive Web Apps', 'React Native', 'Multiplataforma', 'Despliegue en App Store'],
      },
      performanceOptimization: {
        title: 'Optimización de Rendimiento',
        description: 'Acelera tu sitio web y mejora la experiencia del usuario con técnicas avanzadas de optimización.',
        features: ['Core Web Vitals', 'División de Código', 'Optimización de Imágenes', 'Estrategias de Caché'],
      },
      seoAnalytics: {
        title: 'SEO y Analíticas',
        description: 'Mejora tu visibilidad online y rastrea el rendimiento con SEO y analíticas integrales.',
        features: ['SEO Técnico', 'Google Analytics', 'Search Console', 'Monitoreo de Rendimiento'],
      },
      consultation: {
        title: 'Consultoría',
        description: 'Orientación estratégica para tus proyectos digitales, desde el concepto hasta la implementación exitosa.',
        features: ['Planificación de Proyectos', 'Selección de Stack Tecnológico', 'Diseño de Arquitectura', 'Entrenamiento de Equipos'],
      },
    },
    // FANTASMA Section
    fantasma: {
      title: 'FANTASMA',
      description: 'Explorando la intersección de sueños y realidad digital a través del machinima',
      projects: {
        dreamscape: {
          title: 'Paisaje Digital de Sueños',
          description: 'Una exploración de narrativas subconscientes a través de medios interactivos.',
        },
        chaos: {
          title: 'Caos Controlado',
          description: 'Donde la aleatoriedad se encuentra con la intención en la narrativa digital.',
        },
        convergence: {
          title: 'Convergencia de Realidades',
          description: 'La fusión de mundos virtuales y oníricos en forma de machinima.',
        },
      },
    },
    // Experience Section
    experience: {
      title: 'Experiencia',
      description: 'Un viaje a través del desarrollo creativo y la innovación digital',
      stats: {
        projectsCompleted: 'Proyectos Completados',
        yearsExperience: 'Años de Experiencia',
        happyClients: 'Clientes Satisfechos',
        clientSatisfaction: 'Satisfacción del Cliente',
      },
      jobs: {
        seniorCreativeDeveloper: {
          title: 'Desarrollador Creativo Senior',
          company: 'Digital Organic Studio',
          location: 'Remoto',
          period: '2022 - Presente',
          description: 'Liderando el desarrollo de experiencias web innovadoras con enfoque en diseño orgánico y animaciones suaves.',
          achievements: [
            'Aumenté la satisfacción del cliente en un 40% a través de UX mejorada',
            'Reduje los tiempos de carga de página en un 60% en todos los proyectos',
            'Mentoré a 5 desarrolladores junior',
          ],
        },
        fullStackDeveloper: {
          title: 'Desarrollador Full-Stack',
          company: 'Nature Tech Solutions',
          location: 'San Francisco, CA',
          period: '2020 - 2022',
          description: 'Desarrollé aplicaciones web escalables con énfasis en monitoreo ambiental y visualización de datos.',
          achievements: [
            'Construí un dashboard en tiempo real sirviendo a más de 10k usuarios',
            'Implementé algoritmos de ML para análisis predictivo',
            'Lideré la migración a arquitectura de microservicios',
          ],
        },
        frontendDeveloper: {
          title: 'Desarrollador Frontend',
          company: 'Creative Labs',
          location: 'Nueva York, NY',
          period: '2018 - 2020',
          description: 'Me especialicé en crear sitios web responsivos y accesibles con frameworks modernos de JavaScript.',
          achievements: [
            'Mejoré las puntuaciones de accesibilidad en un 85%',
            'Reduje el tiempo de desarrollo en un 30% con componentes reutilizables',
            'Colaboré con el equipo de diseño en más de 50 proyectos',
          ],
        },
      },
      keyAchievements: 'Logros Clave:',
    },
    // Contact Section
    contact: {
      title: 'Conectemos',
      description: '¿Listo para dar vida a tus ideas? Creemos algo increíble juntos.',
      getInTouch: 'Ponte en Contacto',
      intro: 'Siempre estoy emocionado de discutir nuevos proyectos y oportunidades. Ya sea que tengas una idea específica en mente o necesites orientación en tu viaje digital, estoy aquí para ayudar.',
      contactInfo: {
        email: 'Correo',
        phone: 'Teléfono',
        location: 'Ubicación',
      },
      followMe: 'Sígueme',
      form: {
        name: 'Nombre',
        namePlaceholder: 'Tu nombre',
        email: 'Correo',
        emailPlaceholder: 'tu.correo@ejemplo.com',
        subject: 'Asunto',
        subjectPlaceholder: '¿De qué se trata?',
        message: 'Mensaje',
        messagePlaceholder: 'Cuéntame sobre tu proyecto...',
        sendMessage: 'Enviar Mensaje',
      },
    },
    // Footer
    footer: {
      copyright: '© 2025 RANDOM. Creado con principios de diseño orgánico.',
    },
  },
};

export const t = (language: Language, key: string): string => {
  const keys = key.split('.');
  let value: any = translations[language];
  
  for (const k of keys) {
    value = value?.[k];
  }
  
  return value || key;
};